# VIM::Packager::MakeMaker
#
# This Makefile is generated by VIM::Packager::MakeMaker version $VERSION from
# the contents of META . don't edit this file, edit META file instead.
#
# Author: Cornelius
# Email : cornelius.howl@gmail.com
# 


FULLPERL = /opt/local/bin/perl
NOECHO = @
VIM_AFTERBASE_DIR = /Users/c9s/.vim/after
VIM_AFTER_AFTER_DIR = /Users/c9s/.vim/after
VIM_AFTER_COLORS_DIR = /Users/c9s/.vim/colors
VIM_AFTER_COMPILER_DIR = /Users/c9s/.vim/compiler
VIM_AFTER_DIR = /Users/c9s/.vim/after
VIM_AFTER_FTPLUGIN_DIR = /Users/c9s/.vim/ftplugin
VIM_AFTER_MACROS_DIR = /Users/c9s/.vim/macros
VIM_AFTER_PLUGIN_DIR = /Users/c9s/.vim/plugin
VIM_AFTER_SYNTAX_DIR = /Users/c9s/.vim/syntax
VIM_BASEDIR = /Users/c9s/.vim
VIM_COLORS_DIR = /Users/c9s/.vim/colors
VIM_COMPILER_DIR = /Users/c9s/.vim/compiler
VIM_FTPLUGIN_DIR = /Users/c9s/.vim/ftplugin
VIM_MACROS_DIR = /Users/c9s/.vim/macros
VIM_PLUGIN_DIR = /Users/c9s/.vim/plugin
VIM_SYNTAX_DIR = /Users/c9s/.vim/syntax
TO_INST_VIMS = vimlib/plugin/cpan.vim \
	vimlib/plugin/window.vim \
	vimlib/plugin/p5-function-search.vim \
	vimlib/plugin/ctags-search.vim \
	vimlib/plugin/perl-completion.vim
VIMS_TO_RUNT = vimlib/plugin/cpan.vim \
	$(VIM_BASEDIR)/plugin/cpan.vim \
	vimlib/plugin/window.vim \
	$(VIM_BASEDIR)/plugin/window.vim \
	vimlib/plugin/p5-function-search.vim \
	$(VIM_BASEDIR)/plugin/p5-function-search.vim \
	vimlib/plugin/ctags-search.vim \
	$(VIM_BASEDIR)/plugin/ctags-search.vim \
	vimlib/plugin/perl-completion.vim \
	$(VIM_BASEDIR)/plugin/perl-completion.vim
all : install-deps
install : 

		$(NOECHO) $(FULLPERL) -Ilib -MVIM::Packager::Installer=install -e 'install()' $(VIMS_TO_RUNT) 
install-deps : 
		$(NOECHO) $(FULLPERL) -Ilib -MVIM::Packager::Installer=install_deps_remote  -e 'install_deps_remote()' libperl.vim \
	autoload/libperl.vim \
	http://github.com/c9s/libperl.vim/raw/master/autoload/libperl.vim 
